apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailarchive-pvc
  namespace: mailarchive
  labels:
    app: mailarchive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
